version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: matrix-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/:/etc/nginx/conf.d/
      ports:
          - "80:80"

    php-fpm:
      build: docker/php-fpm
      container_name: matrix-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini